import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { parseDocument } from './parsing'
import { chunkDocument } from './chunking'

// Exercises the real parsers (unpdf, mammoth) against real binary files, not
// mocks. The unit tests elsewhere in this repo can't catch a parser that
// technically runs but silently returns garbage or drops pages -- this is
// the check for that. Fixtures generated by scripts/test-fixtures/make-*.mjs.
const FIXTURES = path.join(process.cwd(), 'scripts/test-fixtures')

describe('parseDocument against a real PDF', () => {
  it('extracts real per-page text with correct page numbers', async () => {
    const buffer = fs.readFileSync(path.join(FIXTURES, 'chunking-strategies.pdf'))
    const parsed = await parseDocument(buffer, 'application/pdf')

    expect(parsed.parser).toBe('pdf')
    expect(parsed.pages).toHaveLength(2)
    expect(parsed.pages[0].pageNumber).toBe(1)
    expect(parsed.pages[1].pageNumber).toBe(2)
    expect(parsed.pages[0].text).toContain('Fixed-size chunking')
    expect(parsed.pages[1].text).toContain('Chunking Failure Modes')
    // Content from page 2 must not leak into page 1's extracted text.
    expect(parsed.pages[0].text).not.toContain('Failure Modes')
  })

  it('chunks the extracted PDF text with correct page provenance', async () => {
    const buffer = fs.readFileSync(path.join(FIXTURES, 'chunking-strategies.pdf'))
    const parsed = await parseDocument(buffer, 'application/pdf')
    const chunks = chunkDocument(parsed)

    expect(chunks.length).toBeGreaterThan(0)
    expect(chunks.every((c) => c.parser === 'pdf')).toBe(true)
    const page1Chunks = chunks.filter((c) => c.sourcePage === 1)
    const page2Chunks = chunks.filter((c) => c.sourcePage === 2)
    expect(page1Chunks.length).toBeGreaterThan(0)
    expect(page2Chunks.length).toBeGreaterThan(0)
  })
})

describe('parseDocument against a real DOCX', () => {
  it('extracts real text via mammoth', async () => {
    const buffer = fs.readFileSync(path.join(FIXTURES, 'hybrid-retrieval.docx'))
    const parsed = await parseDocument(buffer, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')

    expect(parsed.parser).toBe('docx')
    expect(parsed.pages).toHaveLength(1) // docx has no native pagination
    expect(parsed.pages[0].pageNumber).toBeNull()
    expect(parsed.pages[0].text).toContain('Hybrid retrieval combines dense vector search')
    expect(parsed.pages[0].text).toContain('reciprocal rank fusion')
  })
})

describe('parseDocument against a real plain-text file', () => {
  it('passes text through unchanged', async () => {
    const buffer = fs.readFileSync(path.join(FIXTURES, 'reranking.txt'))
    const parsed = await parseDocument(buffer, 'text/plain')

    expect(parsed.parser).toBe('text')
    expect(parsed.pages[0].text).toContain('cross-encoder reranker')
  })
})
