import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

// Shared GFM markdown renderer (tables, bold/italic, lists, code fences) for
// long-form text that comes from outside the app -- workstream goals/
// guardrails and workstream_artifacts content/notes, both free text a
// consultant or curator pastes in, often already markdown-formatted (e.g. a
// findings report generated by an external tool). Element styling matches
// the zinc palette used across the projects/ UI rather than pulling in
// @tailwindcss/typography for one component.
export function Markdown({ text }: { text: string }) {
  return (
    <div className="text-sm leading-relaxed text-zinc-800">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          h1: ({ children }) => <h2 className="mb-2 mt-4 text-base font-semibold text-zinc-900 first:mt-0">{children}</h2>,
          h2: ({ children }) => <h3 className="mb-2 mt-4 text-sm font-semibold text-zinc-900 first:mt-0">{children}</h3>,
          h3: ({ children }) => <h4 className="mb-1 mt-3 text-sm font-semibold text-zinc-900 first:mt-0">{children}</h4>,
          p: ({ children }) => <p className="mb-3 last:mb-0">{children}</p>,
          ul: ({ children }) => <ul className="mb-3 list-disc pl-5 last:mb-0">{children}</ul>,
          ol: ({ children }) => <ol className="mb-3 list-decimal pl-5 last:mb-0">{children}</ol>,
          li: ({ children }) => <li className="mb-1">{children}</li>,
          strong: ({ children }) => <strong className="font-semibold text-zinc-900">{children}</strong>,
          a: ({ children, href }) => (
            <a href={href} target="_blank" rel="noreferrer" className="text-blue-700 underline">
              {children}
            </a>
          ),
          hr: () => <hr className="my-4 border-zinc-200" />,
          blockquote: ({ children }) => <blockquote className="mb-3 border-l-2 border-zinc-300 pl-3 text-zinc-600 last:mb-0">{children}</blockquote>,
          code: ({ children, className }) => {
            // Fenced blocks carry a `language-*` className from remark; inline
            // code doesn't -- that distinction is what tells them apart here.
            const isBlock = Boolean(className)
            if (isBlock) return <code className={className}>{children}</code>
            return <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-xs text-zinc-800">{children}</code>
          },
          pre: ({ children }) => (
            <pre className="mb-3 overflow-x-auto rounded border border-zinc-200 bg-zinc-50 p-3 font-mono text-xs text-zinc-800 last:mb-0">{children}</pre>
          ),
          table: ({ children }) => (
            <div className="mb-3 overflow-x-auto last:mb-0">
              <table className="w-full border-collapse text-left text-xs">{children}</table>
            </div>
          ),
          thead: ({ children }) => <thead className="bg-zinc-50">{children}</thead>,
          th: ({ children }) => <th className="border border-zinc-200 px-2 py-1.5 font-semibold text-zinc-700">{children}</th>,
          td: ({ children }) => <td className="border border-zinc-200 px-2 py-1.5 align-top text-zinc-700">{children}</td>,
        }}
      >
        {text}
      </ReactMarkdown>
    </div>
  )
}
