'use client'

import { useState, useTransition } from 'react'
import { generateSubstackExportAction } from '@/app/actions/blog'

interface SubstackExportPackage {
  fullArticleHtml: string
  substackEditionHtml: string
  tags: string[]
  socialPreviewText: string
  substackNote: string
  canonicalUrl: string
  providerName: string
  modelUsed: string
}

function CopyButton({ label, text, onCopied }: { label: string; text: string; onCopied: () => void }) {
  const [copied, setCopied] = useState(false)
  return (
    <button
      type="button"
      onClick={async () => {
        await navigator.clipboard.writeText(text)
        setCopied(true)
        onCopied()
        setTimeout(() => setCopied(false), 1500)
      }}
      className="rounded border border-zinc-300 px-2 py-1 text-xs font-medium text-zinc-700 hover:bg-zinc-100"
    >
      {copied ? 'Copied' : `Copy ${label}`}
    </button>
  )
}

// Editorial export, not a Substack publishing integration -- generates a
// reviewable package (src/lib/blog/substack-export.ts) with per-field Copy
// controls. Never stores Substack credentials, never writes back to the
// draft, never publishes anywhere on its own.
export function SubstackExportPanel({ postId }: { postId: string }) {
  const [open, setOpen] = useState(false)
  const [pkg, setPkg] = useState<SubstackExportPackage | null>(null)
  const [variant, setVariant] = useState<'full' | 'edition'>('edition')
  const [error, setError] = useState<string | null>(null)
  const [hasCopiedOnce, setHasCopiedOnce] = useState(false)
  const [isPending, startTransition] = useTransition()

  function handleGenerate() {
    setError(null)
    setOpen(true)
    startTransition(async () => {
      try {
        const result = await generateSubstackExportAction(postId)
        setPkg(result as SubstackExportPackage)
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to prepare the Substack export')
      }
    })
  }

  const html = pkg ? (variant === 'full' ? pkg.fullArticleHtml : pkg.substackEditionHtml) : ''

  return (
    <div className="rounded border border-zinc-200 bg-white p-4">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-semibold">Prepare for Substack</h3>
        <button
          type="button"
          disabled={isPending}
          onClick={handleGenerate}
          className="rounded border border-zinc-300 px-3 py-1.5 text-sm disabled:opacity-50"
        >
          {isPending ? 'Preparing…' : open ? 'Regenerate' : 'Prepare for Substack'}
        </button>
      </div>

      {open && (
        <div className="mt-3 flex flex-col gap-3">
          {error && <p className="text-sm text-red-600">{error}</p>}
          {isPending && !pkg && <p className="text-sm text-zinc-500">Generating with the active structured-output model…</p>}

          {pkg && (
            <>
              <p className="text-xs text-zinc-500">
                Generated by {pkg.providerName} ({pkg.modelUsed}). Review everything before pasting into Substack -- this never publishes anything on
                its own and never modifies the original draft.
              </p>

              <div className="flex gap-2 text-xs">
                <button
                  type="button"
                  onClick={() => setVariant('edition')}
                  className={`rounded-full px-2.5 py-1 ${variant === 'edition' ? 'bg-zinc-900 text-white' : 'bg-zinc-100 text-zinc-600'}`}
                >
                  Substack edition (recommended)
                </button>
                <button
                  type="button"
                  onClick={() => setVariant('full')}
                  className={`rounded-full px-2.5 py-1 ${variant === 'full' ? 'bg-zinc-900 text-white' : 'bg-zinc-100 text-zinc-600'}`}
                >
                  Full article
                </button>
              </div>

              <div className="flex items-center justify-between">
                <span className="text-xs font-medium text-zinc-500">{variant === 'edition' ? 'Substack edition HTML' : 'Full article HTML'}</span>
                <CopyButton label="HTML" text={html} onCopied={() => setHasCopiedOnce(true)} />
              </div>
              <div
                className="max-h-64 overflow-y-auto rounded border border-zinc-200 bg-zinc-50 p-3 text-sm"
                // Safe to render directly -- this HTML is generated
                // server-side by our own Markdown component (a fixed,
                // known set of tags, no raw-HTML passthrough), never by
                // interpreting arbitrary third-party markup at display time.
                dangerouslySetInnerHTML={{ __html: html }}
              />

              <div className="flex items-center justify-between">
                <span className="text-xs font-medium text-zinc-500">Suggested tags</span>
                <CopyButton label="tags" text={pkg.tags.join(', ')} onCopied={() => setHasCopiedOnce(true)} />
              </div>
              <p className="text-sm text-zinc-700">{pkg.tags.join(', ') || '(none suggested)'}</p>

              <div className="flex items-center justify-between">
                <span className="text-xs font-medium text-zinc-500">Social preview text</span>
                <CopyButton label="text" text={pkg.socialPreviewText} onCopied={() => setHasCopiedOnce(true)} />
              </div>
              <p className="text-sm text-zinc-700">{pkg.socialPreviewText}</p>

              <div className="flex items-center justify-between">
                <span className="text-xs font-medium text-zinc-500">Suggested Substack Note</span>
                <CopyButton label="Note" text={pkg.substackNote} onCopied={() => setHasCopiedOnce(true)} />
              </div>
              <p className="text-sm text-zinc-700">{pkg.substackNote}</p>

              <div className="flex items-center justify-between">
                <span className="text-xs font-medium text-zinc-500">Canonical KB Sandbox URL</span>
                <CopyButton label="URL" text={pkg.canonicalUrl} onCopied={() => setHasCopiedOnce(true)} />
              </div>
              <p className="text-sm text-zinc-700">{pkg.canonicalUrl}</p>

              {hasCopiedOnce && (
                <a
                  href="https://substack.com"
                  target="_blank"
                  rel="noreferrer"
                  className="self-start rounded bg-zinc-900 px-3 py-1.5 text-sm font-medium text-white"
                >
                  Open Substack editor
                </a>
              )}
            </>
          )}
        </div>
      )}
    </div>
  )
}
