-- Owner Roadmap and Ember Feedback Board, Phase 1
-- (docs/dev-request-owner-roadmap-and-ember-feedback-board.md). One private
-- board where pilot users report bugs/improvements/feature requests
-- conversationally through Ember, and two specific owner identities triage
-- them -- explicitly not via the existing platform admin/curator roles.

-- platform_owners ------------------------------------------------------------
-- A new, deliberately narrow authorization concept, independent of
-- profiles.role. Seeded with the two authorized identities below; safe/
-- idempotent if either account doesn't exist yet at migration time (simply
-- not seeded -- add later the same way scripts/create-mike-admin.mjs
-- bootstraps accounts). "Design the owner allowlist so it can later move to
-- a governed owner role or membership table without rewriting board
-- records" (dev request) is satisfied by keeping this a table + function
-- checked at read/write time, never denormalized onto feedback_reports rows.
create table platform_owners (
  user_id uuid primary key references profiles(id) on delete cascade,
  email text not null,
  added_by uuid references profiles(id) on delete set null,
  added_at timestamptz not null default now()
);

insert into platform_owners (user_id, email, added_by, added_at)
select id, email, id, now() from profiles where email in ('mike.aguilar@gmail.com', 'mikecolligodata@gmail.com')
on conflict (user_id) do nothing;

-- Deliberately NO is_admin(uid) OR ... bypass, unlike every other helper
-- function in this schema -- "platform admin status alone does not grant
-- owner-board access" (dev request, Guardrails). Same shape as is_admin/
-- is_curator_or_admin (20260808190009_functions.sql) otherwise.
create or replace function is_platform_owner(uid uuid)
returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from platform_owners where user_id = uid);
$$;

alter table platform_owners enable row level security;
create policy "platform_owners_select_owner" on platform_owners
  for select using (is_platform_owner(auth.uid()));
-- No insert/update/delete policy -- membership changes go through a future
-- migration or admin-client script, not the running application, matching
-- the dev request's "do not rely only on hidden navigation ... design the
-- owner allowlist so it can later move to a governed role."

-- conversations.kind ----------------------------------------------------------
-- Orthogonal to project_id (20260824190001_conversations_project_binding.sql)
-- -- a Feedback conversation with Ember is never resumed and never shown in
-- the normal History list, so it needs to be distinguishable from an
-- ordinary chat conversation without overloading project_id (a feedback
-- conversation may still happen to be started from a project page, but that
-- doesn't make it project-bound in the existing sense).
alter table conversations add column kind text not null default 'chat' check (kind in ('chat', 'feedback'));

-- feedback_reports -------------------------------------------------------------
create table feedback_reports (
  id uuid primary key default gen_random_uuid(),
  -- Human-friendly "FB-123" shown to the reporter -- separate from the uuid
  -- primary key, same reasoning as eval_runs/graph_runs using a uuid
  -- internally while display surfaces prefer something shorter elsewhere.
  report_number bigint generated by default as identity unique,
  reporter_id uuid not null references profiles(id) on delete cascade,
  -- The Ember conversation that produced this report, for provenance --
  -- never a pointer to a general chat conversation (kind is always
  -- 'feedback' for this column's target, though not DB-enforced across
  -- tables).
  source_conversation_id uuid references conversations(id) on delete set null,
  type text not null check (type in ('bug', 'improvement', 'feature_request', 'usability', 'documentation')),
  title text not null,
  description text not null,
  expected_result text,
  actual_result text,
  impact text,
  reproduction_steps text,
  severity text check (severity in ('critical', 'high', 'medium', 'low')),
  status text not null default 'new'
    check (status in ('new', 'triaged', 'accepted', 'deferred', 'declined', 'in_progress', 'ready_to_verify', 'resolved')),
  -- "Suspected security or privacy incidents require a confidential
  -- classification and restricted notification path rather than ordinary
  -- board visibility" (dev request) -- the restricted-visibility mechanics
  -- (RLS) are identical to 'standard' in this phase; only the label and
  -- board filterability exist yet. Actual separate notification is
  -- deliberately deferred, see the roadmap entry.
  classification text not null default 'standard' check (classification in ('standard', 'confidential_security')),
  -- Informational only -- never used to grant access to a project's
  -- underlying restricted content ("project association does not
  -- automatically expose restricted project evidence to board triagers",
  -- dev request Guardrails).
  current_page text,
  project_id uuid references projects(id) on delete set null,
  application_version text,
  environment text,
  duplicate_of uuid references feedback_reports(id) on delete set null,
  owner_decision text,
  owner_decision_rationale text,
  affected_version text,
  fixed_version text,
  deployed_version text,
  assignee_id uuid references profiles(id) on delete set null,
  -- e.g. "OR-018" once an accepted item graduates into the owner roadmap
  -- register (docs/commercial/ROADMAP.md) -- set manually by an owner, not
  -- derived.
  roadmap_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index feedback_reports_reporter_id_idx on feedback_reports(reporter_id);
create index feedback_reports_status_idx on feedback_reports(status);

create trigger feedback_reports_set_updated_at before update on feedback_reports
  for each row execute function set_updated_at();

-- feedback_report_status_history -----------------------------------------------
-- Insert-only -- "preserve an auditable history of classification, status
-- and owner-decision changes" (dev request). Unlike
-- resource_access_audit_log, this is safe to gate with an ordinary RLS
-- insert policy (not an admin-client-only write) because the only actor
-- who can ever write here is already the narrowest possible role (a
-- platform owner) -- there's no lower-trust actor (e.g. a project owner)
-- this needs to be protected from.
create table feedback_report_status_history (
  id uuid primary key default gen_random_uuid(),
  feedback_report_id uuid not null references feedback_reports(id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_by uuid references profiles(id) on delete set null,
  reason text,
  created_at timestamptz not null default now()
);

create index feedback_report_status_history_report_id_idx on feedback_report_status_history(feedback_report_id);

-- RLS ---------------------------------------------------------------------------
alter table feedback_reports enable row level security;

create policy "feedback_reports_select_own_or_owner" on feedback_reports
  for select using (reporter_id = auth.uid() or is_platform_owner(auth.uid()));

create policy "feedback_reports_insert_own" on feedback_reports
  for insert with check (reporter_id = auth.uid());

-- Reporters don't edit after submission -- Ember's Send is the final draft
-- ("submits only after Send", dev request). Only an owner triages.
create policy "feedback_reports_update_owner" on feedback_reports
  for update using (is_platform_owner(auth.uid())) with check (is_platform_owner(auth.uid()));

-- No delete policy -- an immutable historical record, same convention as
-- workstream_artifacts/resource_access_audit_log.

alter table feedback_report_status_history enable row level security;

create policy "feedback_report_status_history_owner" on feedback_report_status_history
  for all using (is_platform_owner(auth.uid())) with check (is_platform_owner(auth.uid()));
